apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-image
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
      - name: sandbox
        image: kimitest2.azurecr.io/sandbox-image:latest
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-service
  namespace: default
spec:
  selector:
    app: sandbox
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer